In [1]:
import numpy as np 

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
import numpy as np

arr = np.arange(30).reshape(6,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [7]:
#Question 3
#Fill the Arrays with zeros and ones 
import numpy as np

arr = np.zeros((2,4))
print(arr)
arr = np.ones((2,4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#Question 4 
#Create a 2D Array with filler of 7
import numpy as np

arr = np.full((2,4), 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


In [13]:
#Question 5
#Implement Slicing
import numpy as np

arr = np.arange(49).reshape(7,7)
#Prt 1 
print(arr[:,:])
#Prt 2 
print(arr[2:5, 0:3])
#Prt 3
print(arr[0:2, 0:5])
#Prt 4
print(arr[2:4, 2:4])
#Prt 5 
print(arr[-3:-1, -3:-1])
#Prt 6 
print(arr[-4:-1, -4:-1])
                

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
[[14 15 16]
 [21 22 23]
 [28 29 30]]
[[ 0  1  2  3  4]
 [ 7  8  9 10 11]]
[[16 17]
 [23 24]]
[[32 33]
 [39 40]]
[[24 25 26]
 [31 32 33]
 [38 39 40]]


In [19]:
#Question 6
#Check the dimensions of Array
import numpy as np

arr = np.array([1,2,3,4])
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [23]:
#Question 7
#Create 8D array with value [2, 2, 2, 2]
import numpy as np

arr = np.array([2, 2, 2, 2], ndmin = 8)
print(arr)

[[[[[[[[2 2 2 2]]]]]]]]
